### PR TITLE
Create file structure, add sample test for scrape function

### PR DESCRIPTION
**Pull request by icecrasher321**
Created a structured project to improve aspects related to scalability(to eventually evolve into a simple  API).

### CODE REVIEW

**Comment by sleepypikachu** [comment]
Thanks for this PR. Unfortunately I can't merge it as it stands.

This adds a lot of binary files as well as .DS_Store files. These are undesirable so I won't merge them in.

I like what you've done with the package structure but you've changed the namespace so it's not in line with the repository (I'm pretty sure I don't want the html pacakge sources in the repo, there is a tool that lets you manage dependencies that way but without committing the sources). You need to make sure that you run go fmt on your files before you commit them so that you don't create unnecessary diffs in the history (e.g. package imports out of order/incorrect indentation).

I think the correct way to add these changes is check out this repository as normal
`go get -u github.com/sleepypikachu/still-good-food`
Then add your clone as a remote so that you preserve the namespace and commit to the clone. If you want to set it up so that it works with an internalised copy of the repos then feel free to check out godep which I would merge if it works.

Very interested in seeing how your tests work so I hope you can get those running but currently I'm having difficulty running them.

**Comment by icecrasher321** [comment]
Thanks for the feedback. I’ll get to it immediately. I like the way this scraper can be used a simple API for building applications(food related) for IOTG devices such as the Amazon Echo(as BBCfood, as per my knowledge, does not have its own API).
-Vikhyath Mondreti

**Comment by icecrasher321** [comment]
Fixed the issues. Tests should work (using go test in the food folder).
-Vikhyath Mondreti

**Comment by sleepypikachu** [comment]
Hi Vikhyath,

Thanks for fixing these issues. I'm really keen to get these changes in but the repository is still organised strangely. You seem to have committed an entire gopath rather than a single repository. When I switch to your branch from my checkout main.go and the food package end up:
`$GOPATH/src/github.com/sleepypikachu/still-good-food/src/github.com/icecrasher321`
but they should end up
`$GOPATH/src/github.com/sleepypikachu/still-good-food/`
This is significant because go build doesn't work in the correct path with your changes. At this point the easiest thing to do is probably to repatch your changes by hand into a fresh copy of the repository.

To achieve this:

Check out the current master from this repository
`go get -u github.com/sleepypikachu/still-good-food`

Head into the repo
`cd $GOPATH/src/github.com/sleepypikachu/still-good-food`

Manually copy in your changes, such as the new main.go and food/Scrape.go without the breaking changes like committing goquery (Don't forget to run go fmt on all your sources!)

Make sure you can run go build and go test at the root of the repository.

Then set up a new remote and push your changes to that (you probably want to create a new branch on your repo from before your first commit for this since we don't want to muddy the history with adding and removing your other changes!)

Once you've pushed your changes to the new branch then we should be good to go if you set up a new pull request :-) Feel free to ping me if you get stuck.

**Comment by sleepypikachu** [comment]
See https://github.com/sleepypikachu/still-good-food/pull/3#issuecomment-228553503

**Pull request closed without merging**
